name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - uses: CultureHQ/actions-yarn@master
    - name: install, lint, build
      run: |
        yarn
        yarn lint
        yarn build
      env:
        CI: true
