name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - uses: CultureHQ/actions-yarn@master
    - name: install
      run: yarn
      env:
        CI: true
    - name: lint
      run: yarn lint
      env:
        CI: true
    - name: build
      run: yarn build
      env:
        CI: true
